
name: Npmjs Package Publishing

on:
  push:
    branches:
      - m

jobs:
  test_os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: OS test for ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm install
          npm test

  test_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ 4.x, 6.x, 8.x, 10.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Versions test for ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm test

  publish-npm:
    needs: [ test_os, test_versions ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
