
name: Simple test on push

on: push

jobs:
  test_simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Simple test
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm install
          npm test